[package]
name = "rock-paper-paradise"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15" }
bevy_prng = { version = "0.9.0", features = ["wyrand"] }
bevy_rand = "0.9.0"

derive_more = { version = "1.0", features = ["full"] }
itertools = { version = "0.13" }
rand = "0.8"
